version: "3"
vars:
  GREETING: Hello, World!
env:
  NO_COLOR: 1
  COLOR: false
output: prefixed
tasks:
  default:
    cmds:
    - task: get-schema
    - task: get-versions
    - task: import-task-schema
    deps:
    - git-ensure-clean
  hello:
    cmds:
    - echo "{{.GREETING}}"
    silent: true
  import-task-schema:
    cmds:
    - cue import --path '#task:' --package task schema.json --force
  import-task-schema-workaround:
    cmds:
    - cue import --path '#task:' --package task schema-workaround.json --force
  get-schema:
    cmds:
    - curl -LO https://raw.githubusercontent.com/go-task/task/main/website/static/schema.json
    status:
    - test -f schema.json
  get-versions:
    cmds:
    - task --version
    - cue version
  git-ensure-clean:
    cmds:
    - test -z "$(git status --porcelain --untracked=no)"
  highlight-offending-lines:
    cmds:
    - nl schema.json | sed -n '284,294p' | awk '{ if ($1 == "289") printf "\033[1;31m"; print $0 "\033[0m" }'
    - nl schema.json | sed -n '570,580p' | awk '{ if ($1 == "575") printf "\033[1;31m"; print $0 "\033[0m" }'
