version: "3"
output: prefixed
tasks:
  happy:
    cmds:
    - task: setup
    - task: import-task-schema-workaround
    - test -s schema.cue
  sad:
    cmds:
    - task: setup
    - task: import-task-schema
  setup:
    cmds:
    - task: clean
    - task: get-schema
    - task: get-versions
    deps:
    - git-ensure-clean
  default:
    cmds:
    - task: sad
  hello:
    cmds:
    - echo foo
    silent: true
  clean:
    cmds:
    - rm -f schema.cue
    status:
    - ! test -s schema.cue
  diff:
    cmds:
    - diff -uw schema.json schema-workaround.json || true
  import-task-schema:
    cmds:
    - cue import --force --outfile=schema.cue --simplify --path='#task:' --package=task schema.json 
  import-task-schema-workaround:
    cmds:
    - cue import --force --outfile=schema.cue --simplify --path='#task:' --package=task schema-workaround.json
  get-schema:
    cmds:
    - curl -LO https://raw.githubusercontent.com/go-task/task/main/website/static/schema.json
    status:
    - test -f schema.json
  get-versions:
    cmds:
    - task --version
    - cue version
  git-ensure-clean:
    cmds:
    - test -z "$(git status --porcelain --untracked=no)"
  highlight-offending-lines:
    cmds:
    - nl schema.json | sed -n '284,294p' | awk '{ if ($1 == "289") printf "\033[1;31m"; print $0 "\033[0m" }'
    - nl schema.json | sed -n '570,580p' | awk '{ if ($1 == "575") printf "\033[1;31m"; print $0 "\033[0m" }'
